version: '3.8'

services:
  gocrud:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    command: ["bash"]
